<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-01-26T17:17:09 IST" name="Default suite" finished-at="2022-01-26T17:17:37 IST" duration-ms="28066">
    <groups>
    </groups>
    <test started-at="2022-01-26T17:17:09 IST" name="Default test" finished-at="2022-01-26T17:17:37 IST" duration-ms="28066">
      <class name="com.aspireapp.test.TestPage">
        <test-method is-config="true" signature="browserInit()[pri:0, instance:com.aspireapp.test.TestPage@41e36e46]" started-at="2022-01-26T17:17:09 IST" name="browserInit" finished-at="2022-01-26T17:17:12 IST" duration-ms="2974" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserInit -->
        <test-method signature="login()[pri:1, instance:com.aspireapp.test.TestPage@41e36e46]" started-at="2022-01-26T17:17:12 IST" name="login" finished-at="2022-01-26T17:17:15 IST" duration-ms="2698" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="createNewProduct()[pri:2, instance:com.aspireapp.test.TestPage@41e36e46]" started-at="2022-01-26T17:17:15 IST" name="createNewProduct" finished-at="2022-01-26T17:17:21 IST" duration-ms="6454" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewProduct -->
        <test-method signature="createManufactureProduct()[pri:3, instance:com.aspireapp.test.TestPage@41e36e46]" started-at="2022-01-26T17:17:21 IST" name="createManufactureProduct" finished-at="2022-01-26T17:17:35 IST" duration-ms="13880" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createManufactureProduct -->
        <test-method signature="verifyProductDetails()[pri:4, instance:com.aspireapp.test.TestPage@41e36e46]" started-at="2022-01-26T17:17:35 IST" name="verifyProductDetails" finished-at="2022-01-26T17:17:36 IST" duration-ms="1380" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.aspireapp.test.TestPage.verifyProductDetails(TestPage.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductDetails -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.aspireapp.test.TestPage@41e36e46]" started-at="2022-01-26T17:17:36 IST" name="tearDown" finished-at="2022-01-26T17:17:37 IST" duration-ms="653" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.aspireapp.test.TestPage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
